services:
  postgres:
    image: postgres:16
    container_name: cesi_postgres
    environment:
      POSTGRES_USER: cesi
      POSTGRES_PASSWORD: cesi_password
      POSTGRES_DB: cesi_access
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:2
    container_name: cesi_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  backend:
    build: ./backend
    container_name: cesi_backend
    environment:
      - PORT=8080

      # PostgreSQL
      - DATABASE_URL=postgresql://cesi:cesi_password@postgres:5432/cesi_access

      # Sécurité
      - JWT_SECRET=CHANGE_ME_SUPER_SECRET
      - PRESENCE_BADGE_WINDOW_MS=120000
      - ALERT_COOLDOWN_MS=60000

      # SMTP (optionnel)
      - SMTP_HOST=
      - SMTP_PORT=587
      - SMTP_USER=
      - SMTP_PASS=
      - ALERT_EMAIL_TO=securite@cesi.fr
      - ALERT_EMAIL_FROM=robot@cesi.fr

      # MQTT
      - MQTT_URL=mqtt://mqtt:1883
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=admin123
      - MQTT_ROOT_TOPIC=CESI/#

    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mqtt

  frontend:
    build: ./frontend
    container_name: cesi_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pg_data:
